
// Find all users, if authenticated
GET http://localhost:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg

###
// Delete user
DELETE  http://localhost:8080/user/60ac0f3a24d29051c4e71d6b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg

###
//Get single user
GET http://localhost:8080/user/123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg
###

//Delete all users
DELETE http://localhost:8080/user/deleteAllWithID/UserTest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg

###

// CREATE USER (AS ADMIN, WILL WORK)
POST http://localhost:8080/user/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo4ODgsImlhdCI6MTYyMjA2MDk4MSwiZXhwIjoxNjIzNjgzMzQyNDUwfQ.UNymtACrJlhRvCz_nl23YN3LBDKTTVeijsmwmhuBOoY
Content-Type:  application/json

{
  "id": 344,
  "userName": "Test",
  "email": "test@gmail.com",
  "password": "12345",
  "isAdministrator": false
}
###

// CREATE USER (AS BASIC USER, WILL NOT WORK)
POST http://localhost:8080/user/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxMjMsImlhdCI6MTYyMjA2Nzg1NSwiZXhwIjoxNjIzNjkwMjIzMDg0fQ.dyn558xxekxy8i72qlV2YTBwWCBygDkwIWAPCuh8eDE
Content-Type:  application/json

{
  "id": 373,
  "userName": "ZZZZ",
  "email": "ilhan@gmail.com",
  "password": "12345",
  "isAdministrator": false
}
###

//Create Admin
POST http://localhost:8080/user/register
Content-Type:  application/json

{
  "id": 888,
  "userName": "Admin",
  "email": "admin@gmail.com",
  "password": "12345",
  "isAdministrator": true
}

###

//WIP Update single user
PUT   http://localhost:8080/user/123
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg
Content-Type:  application/json

{
  "userName": "(Updated) Yakup Köhne"
}

###

//WIP Find single user

