//CREATE GROUP
POST https://localhost:8080/group/createGroup
Content-Type: application/json

{
    "groupName": "Test asdsGsasdasddaroup",
    "members": []
}

###
//UPDATE GROUP
PUT https://localhost:8080/group/
Content-Type: application/json

{

    "oldGroupName": "Changed Name for Group",
    "newGroupName": "123Group"
}
###

//GET ALL GROUPS
GET https://localhost:8080/group
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg

###

//DELETE GROUP
DELETE https://localhost:8080/group/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg
Content-Type: application/json

{
    "groupName": "admins group"
}
###

//REMOVE LAST ADDED MEMBER
PUT https://localhost:8080/group/removeLast/111
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg

###

//SUBSCRIBE USER TO GROUP
PUT https://localhost:8080/group/subscribeUser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg
Content-Type: application/json

{
    "userName": "TestNutzer1",
    "groupName": "Test Group"
}
###

//GET GROUPS THE USER IS SUBSCIBED TO
GET https://localhost:8080/group/groupsOf/251572
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg


