
// FIND ALL USERS
GET https://localhost:8080/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg

###

//GET SINGLE USER
GET https://localhost:8080/user/6180770ab0b07b4f88315e1a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg

###

// CREATE USER (AS ADMIN, SHOULD WORK)
POST https://localhost:8080/user/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo5OTksImlhdCI6MTYyMjEzMjQ4NiwiZXhwIjoxNjIzNzU0OTE4OTY3fQ.Z3b9U00xfssIlWo4bdW7u_whDPasTRBRkNMFbTBr0S8
Content-Type:  application/json

{
  "userName": "TTTasd",
  "email": "ykohne@gmail.com",
  "password": "12345",
  "isAdministrator": false
}

###

// CREATE USER (AS BASIC USER, SHOULD NOT WORK)
POST https://localhost:8080/user/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoxMjMsImlhdCI6MTYyMjEzMjU1NSwiZXhwIjoxNjIzNzU0OTg3OTE5fQ.-IzG-rEKV4NrFTMEfz7ic6g2_WXhoHiX9HTxSG6zkEY
Content-Type:  application/json

{
  "userName": "adjsssssd",
  "email": "ykohne@gmail.com",
  "password": "12345",
  "isAdministrator": false
}

###

//CREATE ADMIN
POST https://localhost:8080/user/register
Content-Type:  application/json

{
  "id": 888,
  "userName": "Admin",
  "email": "admin@gmail.com",
  "password": "12345",
  "isAdministrator": true
}

###

// DELETE SINGLE USER (AS ADMIN, SHOULD WORK)
DELETE  https://localhost:8080/user/60aed1357e5c5f2e44d96133
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjo5OTksImlhdCI6MTYyMjEzMjQ4NiwiZXhwIjoxNjIzNzU0OTE4OTY3fQ.Z3b9U00xfssIlWo4bdW7u_whDPasTRBRkNMFbTBr0S8

###

// DELETE SINGLE USER (AS BASIC USER, SHOULD NOT WORK)
DELETE  https://localhost:8080/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjozMzc5NDYsImlhdCI6MTYyNTc1MTQ1MiwiZXhwIjoxNjI3Mzc3NTAzOTgwfQ.uE0TpFNFMQrHd_jAphF81gpl5UfYmCLZxU7Nrhlcbdg
Content-Type:  application/json

{
  "userName": "sjds"
}
###

//DELETE ALL USERS (WIP)
DELETE https://localhost:8080/user/deleteAllWithID/UserTest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg

###

//UPDATE USER INFO
PUT   https://localhost:8080/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiWWFrdXBXb3JraW5nIiwiaWF0IjoxNjIwMjkyOTQ2LCJleHAiOjE2MjE5MTM1Mzk0NDh9.37eXSyixynMA6fCgAouuRP8Tmk_w1JSh_dHM2oJp_Rg
Content-Type:  application/json

{
  "userName": "Narwal",
  "newUserName": "TestNutzer1",
  "newPassword": "12345"
}

###

